### ISSUE TITLE
Uldaman-cannot be completed without GM commands

### ISSUE THREAD

**Issue by Parkan1986** [ZhengPeiRu21/mod-individual-progression#115]
The last room with stone keepers and pidestal.after activating switch after few secons characters stops doin anything so no stone keepers became attackble.Also this happen with the Boss of Uldaman he also cannot be awaken.Without gm commands this instance is cannot be completed.

**Comment by AlvinZhu** [comment]
https://github.com/ZhengPeiRu21/mod-individual-progression/issues/123#issue-1657549689
this patch will fix it.

**Comment by ZhengPeiRu21** [comment]
I've applied AlvinZhu's suggestions, so this should be resolved in 07bade406422a5679b847e0582cd3b2bb6fc3e8a. Please let me know if you continue to see any issues!

**Comment by Parkan1986** [comment]
> I've applied AlvinZhu's suggestions, so this should be resolved in [07bade4](https://github.com/ZhengPeiRu21/mod-individual-progression/commit/07bade406422a5679b847e0582cd3b2bb6fc3e8a). Please let me know if you continue to see any issues!

after updateand quick testing the dungeon still cannot be completed.nothing works.

**Comment by AlvinZhu** [comment]
> > I've applied AlvinZhu's suggestions, so this should be resolved in [07bade4](https://github.com/ZhengPeiRu21/mod-individual-progression/commit/07bade406422a5679b847e0582cd3b2bb6fc3e8a). Please let me know if you continue to see any issues!
> 
> after update and quick testing the dungeon still cannot be completed.nothing works.

You may need to drop and rebuild the world database. 
you have this issue because the faction of the boss is update to 35 by vanilla_mob_factions.sql.
but the fix just delete the set faction sql statement. not revert the faction of the boss to the right value.

**Comment by Parkan1986** [comment]
i recompiled exe and updated sqls.but i still to destroy world database to reapply all again?damn.
I already used few lua scripts which wee provided here and with lualdaman working.will next time will do full world rebuild.
