### ISSUE TITLE
Consumables being affected by % healing decrease

### ISSUE THREAD

**Issue by ajgration** [ZhengPeiRu21/mod-individual-progression#45]
Wondering if this is intentional or not. Currently, "IndividualProgression.VanillaHealingAdjustment = 0.5" is affecting things like potions, bandages, jewelcrafting statues, trinkets, items etc.

This isn't too major, but it mostly affects classes without any other means of healing themselves. Would there be a way to make only player healing spells be affected by this, or certain classes? Also, to save me making a separate post. I'm assuming stuff like Draenei racial, bloodthirst, evocation glyph, drain life etc. are suffering from this as well? I can understand non-vanilla/tbc stuff getting scaled, though I think stuff that was in the original should give their full values. It makes solo'ing on certain classes a lot more difficult otherwise.

Thoughts?

**Comment by ZhengPeiRu21** [comment]
This is not intentional. These items should have the same effects that they had in their respective content. I will add some logic to exclude them. Thank you again for your issue reports!

**Comment by ZhengPeiRu21** [comment]
This should now be resolved in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/b76857090a19a4240ee390cd8836c21d8360e12a.

**Comment by ajgration** [comment]
Applied new sqls, updated server and it still appears to be broken after the latest update mate. Tested on a level 20 warrior. Wool bandage was healing for 10hp per tick, for a total of 70hp instead of 161hp. Lesser healing potion healed for anywhere from 130-160hp, instead of 140-180hp.

**Comment by ZhengPeiRu21** [comment]
> Applied new sqls, updated server and it still appears to be broken after the latest update mate. Tested on a level 20 warrior. Wool bandage was healing for 10hp per tick, for a total of 70hp instead of 161hp. Lesser healing potion healed for anywhere from 130-160hp, instead of 140-180hp.

If you are updating from an older version, you may still have the old healing reduction auras in your database and on your characters. Deleting with this SQL should resolve this issue:
`DELETE FROM `spell_dbc` WHERE `ID` IN (89502,89503,89504,89506,89508);`
